services:
  - name: backend
    type: web
    runtime: docker
    dockerfilePath: Dockerfile
    envVars:
      - key: DB_HOST
        value: db
      - key: DB_PORT
        value: "3306"
      - key: DB_USER
        value: root
      - key: DB_PASSWORD
        value: root_ps
      - key: DB_NAME
        value: recepita
    plan: free

  - name: db
    type: cron
    runtime: docker
    dockerfilePath: Dockerfile
    schedule: "@daily"
    envVars:
      - key: MYSQL_ROOT_PASSWORD
        value: root_ps
      - key: MYSQL_DATABASE
        value: recepita
      - key: MYSQL_USER
        value: user
      - key: MYSQL_PASSWORD
        value: user_ps

  - name: logserver
    type: cron
    runtime: docker
    dockerfilePath: Dockerfile
    schedule: "@daily"

  - name: grafana
    type: cron
    runtime: docker
    dockerfilePath: Dockerfile
    schedule: "@daily"
