services:
  - type: web
    name: recepita-backend
    runtime: docker
    dockerfilePath: ./Dockerfile
    branch: main
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: DB_HOST
        value: recepita-db
      - key: DB_PORT
        value: 3306
      - key: DB_USER
        value: root
      - key: DB_PASSWORD
        value: root_ps
      - key: DB_NAME
        value: recepita

  - type: web
    name: recepita-db-mariadb
    runtime: docker
    dockerCommand: mariadb:latest
    envVars:
      - key: MYSQL_ROOT_PASSWORD
        value: root_ps
      - key: MYSQL_DATABASE
        value: recepita
      - key: MYSQL_USER
        value: user
      - key: MYSQL_PASSWORD
        value: user_ps

  - type: web
    name: logserver-loki
    runtime: docker
    dockerCommand: grafana/loki:latest
    autoDeploy: true

  - type: web
    name: grafana-dashboard
    runtime: docker
    dockerCommand: grafana/grafana:latest
    autoDeploy: true
